version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app/
    networks:
      - app-tier


  redis:
    image: redis
    ports:
      - 6379
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge